// vue-demo/app/components/Details.vue
<template>
  <Page>
    <ActionBar :title="flick.title"/>

    <ScrollView height="100%">
        <StackLayout>
            <Image
                margin="0"
                stretch="aspectFill"
                :src="flick.image"></Image>
            <StackLayout padding="10 20">
                <StackLayout v-for="detail in flick.details" :key="detail.id">
                    <Label
                        marginTop="15"
                        fontSize="16"
                        fontWeight="700"
                        class="text-primary"
                        textWrap="true"
                        :text="detail.title"></Label>
                    <Label
                        fontSize="14"
                        class="text-secondary"
                        textWrap="true"
                        :text="detail.body"></Label>
                </StackLayout>
            </StackLayout>
        </StackLayout>
    </ScrollView>
</Page>
</template>

<script lang="ts">
  import Vue from "nativescript-vue";
  import FlickService from '../services/FlickService';
  
  const flickService = new FlickService();

  export default Vue.extend({
    props: ['id'],
    data() {
        return {
            flick: flickService.getFlickById(this.id)
        }
    }
  });
</script>

// svelte-tutorial/app/pages/Details.svelte
<page>
    <actionBar title="{flick.title}" />
    <scrollView>
      <stackLayout>
        <image
            margin="0"
            stretch="aspectFill"
            src="{flick.image}"/>
        <stackLayout padding="10 20">
            {#each flick.details as details}
                <stackLayout>
                  <label
                      marginTop="15"
                      fontSize="16"
                      fontWeight="700"
                      class="text-primary"
                      textWrap="true"
                      text="{details.title}"/>
                  <label
                      fontSize="14"
                      class="text-secondary"
                      textWrap="true"
                      text="{details.body}"/>
                </stackLayout>
            {/each}
        </stackLayout>
      </stackLayout>
  </scrollView>
</page>

  <script>
	import { FlickService } from '../services/flickService';

    export let flickId;
    let flick = FlickService.getInstance().getFlickById(flickId);
</script>
