// angular-demo/src/app/features/home/home.component.ts
import { Component } from "@angular/core";
import { ItemEventData } from "@nativescript/core";
import { RouterExtensions } from "@nativescript/angular";
import { FlickService } from "~/app/core";

@Component({
  moduleId: module.id,
  selector: "ns-home",
  templateUrl: "home.component.html"
})
export class HomeComponent {
  flicks = this.flickService.getFlicks();

  constructor(
    private routerExtensions: RouterExtensions,
    private flickService: FlickService
  ) {}

  onFlickTap(args: ItemEventData): void {
    this.routerExtensions.navigate(["details", this.flicks[args.index].id]);
  }
}

<ActionBar title="NativeFlix"></ActionBar>

<ListView
    height="100%"
    separatorColor="transparent"
    [items]="flicks"
    (itemTap)="onFlickTap($event)">
    <ng-template let-item="item">
        <!-- The item template can only have a single root view container (e.g. GridLayout, StackLayout, etc.)-->
        <GridLayout
            height="280"
            borderRadius="10"
            class="bg-secondary"
            rows="*, auto, auto"
            columns="*"
            margin="5 10"
            padding="0">
          <Image
            row="0"
            margin="0"
            stretch="aspectFill"
            [src]="item.image"></Image>
          <Label
            row="1"
            margin="10 10 0 10"
            fontWeight="700"
            class="text-primary"
            fontSize="18"
            [text]="item.title"></Label>
          <Label
            row="2"
            margin="0 10 10 10"
            class="text-secondary"
            fontSize="14"
            textWrap="true"
            [text]="item.description"></Label>
        </GridLayout>
      </ng-template>

</ListView>

// svelte-tutorial/app/pages/Home.svelte
<script>
  import { navigate } from "@nativescript-community/svelte-native";
  import { Template } from "@nativescript-community/svelte-native/components";
  import Details from "./Details.svelte";
  import { FlickService } from "../services/flickService";

  let flicks = FlickService.getInstance().getFlicks();

  function onFlickTap(event) {
    navigate({
      page: Details,
      props: { flickId: flicks[event.index].id },
    });
  }
</script>

<page>
  <actionBar title="NativeFlix" />
  <stackLayout height="100%">
    <listView
      height="100%"
      separatorColor="transparent"
      items={flicks}
      on:itemTap={onFlickTap}
    >
      <Template let:item>
        <gridLayout
          height="280"
          borderRadius="10"
          class="bg-secondary"
          rows="*, auto, auto"
          columns="*"
          margin="5 10"
          padding="0"
        >
          <image row="0" margin="0" stretch="aspectFill" src={item.image} />
          <label
            row="1"
            margin="10 10 0 10"
            fontWeight="700"
            class="text-primary"
            fontSize="18"
            text={item.title}
          />
          <label
            row="2"
            margin="0 10 10 10"
            class="text-secondary"
            fontSize="14"
            textWrap="true"
            text={item.description}
          />
        </gridLayout>
      </Template>
    </listView>
  </stackLayout>
</page>
