// svelte-tutorial/app/pages/Home.svelte
<script>
  import { navigate } from "@nativescript-community/svelte-native";
  import { Template } from "@nativescript-community/svelte-native/components";
  import Details from "./Details.svelte";
  import { FlickService } from "../services/flickService";

  let flicks = FlickService.getInstance().getFlicks();

  function onFlickTap(event) {
    navigate({
      page: Details,
      props: { flickId: flicks[event.index].id },
    });
  }
</script>

<page>
  <actionBar title="NativeFlix" />
  <stackLayout height="100%">
    <listView
      height="100%"
      separatorColor="transparent"
      items={flicks}
      on:itemTap={onFlickTap}
    >
      <Template let:item>
        <gridLayout
          height="280"
          borderRadius="10"
          class="bg-secondary"
          rows="*, auto, auto"
          columns="*"
          margin="5 10"
          padding="0"
        >
          <image row="0" margin="0" stretch="aspectFill" src={item.image} />
          <label
            row="1"
            margin="10 10 0 10"
            fontWeight="700"
            class="text-primary"
            fontSize="18"
            text={item.title}
          />
          <label
            row="2"
            margin="0 10 10 10"
            class="text-secondary"
            fontSize="14"
            textWrap="true"
            text={item.description}
          />
        </gridLayout>
      </Template>
    </listView>
  </stackLayout>
</page>

// vue-tutorial/app/components/Home.vue
<template>
  <Page>
    <ActionBar title="NativeFlix" />
    
    <ListView
        height="100%"
        separatorColor="transparent"
        :items="flicks"
        @itemTap="onFlickTap">
        <template #default="{ item }">
            <GridLayout
                height="280"
                borderRadius="10"
                class="bg-secondary"
                rows="*, auto, auto"
                columns="*"
                margin="5 10"
                padding="0">
              <Image
                row="0"
                margin="0"
                stretch="aspectFill"
                :src="item.image" />
              <Label
                row="1"
                margin="10 10 0 10"
                fontWeight="700"
                class="text-primary"
                fontSize="18"
                :text="item.title" />
              <Label
                row="2"
                margin="0 10 10 10"
                class="text-secondary"
                fontSize="14"
                textWrap="true"
                :text="item.description" />
            </GridLayout>
          </template>
    </ListView>
  </Page>
</template>

<script lang="ts">
  import { defineComponent } from "nativescript-vue";
  import FlickService from '../services/FlickService';
  import Details from './Details.vue';
  import type { FlickModel } from '../models/Flick';

  const flickService = new FlickService();

  export default defineComponent({
    data() {
      return {
        flicks: flickService.getFlicks() as FlickModel[]
      }
    },
    methods: {
      onFlickTap(args: { item?: FlickModel; index?: number }) {
        const item = args.item || (typeof args.index === 'number' ? this.flicks[args.index] : undefined);
        if (!item) {
          return;
        }
        const id = item.id;
        this.$navigateTo(Details, {
          props: { id }
        });
      }
    }
  });
</script>
